### ISSUE TITLE
Box2d shouldn't be as external repo

### ISSUE THREAD

**Issue by keymone** [maxfish/gojira2d#16]
golang has fairly good tooling to pull external libraries from github, all we need to do is:

- run `go get -u github.com/ByteArena/box2d`
- refer to that package in imports: `import "ByteArena/box2d"`
- add that information to README :)

**Comment by maxfish** [comment]
Yep, I and @Yuto3S already discussed this. We should remove that submodule

**Comment by maxfish** [comment]
Submodule removed
