### ISSUE TITLE
Add a test coverage tool to the repo

### ISSUE THREAD

**Issue by maxfish** [maxfish/gojira2d#38]

**Comment by maxfish** [comment]
I've enabled coveralls.io and added a badge to the readme, but the travis integration is still missing

**Comment by maxfish** [comment]
FYI @keymone

**Comment by keymone** [comment]
@maxfish i think you need to (re)create coveralls api token and put it in travis. i get a feeling it needs repo owner to do it.

**Comment by maxfish** [comment]
Hmm, on the coveralls website they say: "Note: Do not make your repo token public."

This is what I see:
![screen shot 2018-08-08 at 19 46 35](https://user-images.githubusercontent.com/1917764/43854737-16a1fd94-9b44-11e8-9d8b-aed73ba13dc9.png)

**Comment by keymone** [comment]
yeah, don't put it in any  file, just change COVERALLS_TOKEN value here: https://travis-ci.org/maxfish/gojira2d/settings

**Comment by maxfish** [comment]
It worked, thanks!
