### ISSUE TITLE
Rendering problems with GTX970

### ISSUE THREAD

**Issue by maxfish** [maxfish/gojira2d#9]
It looks like that the last vertex is missing.
I've tested it on MacOSX 10.11.6, here are the details of the GPU

```
VIDIA GeForce GTX 970:

  Chipset Model:	NVIDIA GeForce GTX 970
  Type:	GPU
  Bus:	PCIe
  PCIe Lane Width:	x16
  VRAM (Total):	4095 MB
  Vendor:	NVIDIA (0x10de)
  Device ID:	0x13c2
  Revision ID:	0x00a1
  ROM Revision:	VBIOS 84.04.36.00.5e
  Displays:
PHL 234E5:
  Resolution:	1920 x 1080 @ 60Hz (1080p)
  Pixel Depth:	32-Bit Color (ARGB8888)
  Display Serial Number:	UHB1424006540
  Main Display:	Yes
  Mirror:	Off
  Online:	Yes
  Rotation:	Supported
  Television:	Yes

```

![screen shot 2018-04-08 at 21 21 40](https://user-images.githubusercontent.com/1917764/38471538-f4229cb4-3b72-11e8-9ba5-c788bcfafc10.png)
![screen shot 2018-04-08 at 20 30 02](https://user-images.githubusercontent.com/1917764/38471539-f45cda96-3b72-11e8-8da5-fa9d627325f3.png)

**Comment by keymone** [comment]
that's weird, gfx_quads wors fine on master on my mac (radeon gpu), any ideas what this might be?

**Comment by maxfish** [comment]
Yep, wrong parameters passed during the creation of the vertices arrays... Copy&Paste mistake that works on the other GPUs

**Comment by maxfish** [comment]
Tested master with the new changes and the rendering now works.
Stride's value was wrong, in our case it has to be 0
Also the size of a Vertex has to be 2 since we have only 2 components
